<%@ include file="../../includes/jsp_global.jsp" %>

<!doctype html>
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
	<head>
	<!-- Render the common head tags to include CSS and JS files -->
		<%@ include file="../../includes/common_head.jsp" %>
	</head>
	
	<body>
		<%@ include file="../../includes/header.jsp" %>
		<div id="main-container" class="container">
			
				<div id="main-content-container" class="row non-home-container">
				
					<div class="row bread-crumb-container">
						<div class="col-md-12">
							<script>document.write(breadcrumbs);</script>
						</div>
					</div>
					<div id="product-title" class="row">
						<h1>GLOBAL RELAY MASTER TERMS OF SERVICE (RESOLD CUSTOMERS)</h1>
					</div>
					<div class="main-content row">
					
						<div class="col-md-12 left-container">
							<div class="description">
								
								<p>Global Relay Communications Inc. (“<span class="bold">Global Relay</span>”) has developed and owns all the rights to its enterprise message archiving (“<span class="bold">Global Relay Archive</span>”), compliance supervision (“<span class="bold">Compliance Reviewer</span>”), web and mobile archive access (“<span class="bold">Global Relay Search</span>”) and instant messaging (“<span class="bold">Global Relay Message</span>”) services, and specializes in industry-specific online messaging and data compliance solutions.</p>
								<p class="bold">1. AGREEMENT</p>
								<p><span class="bold">1.1. Agreement Documents.</span> These Global Relay Master Terms of Service: Resold Customer Version (the “<span class="bold">Master Terms of Service RCV</span>” or “<span class="bold">MTOS RCV</span>”) set out the framework terms and conditions on which Global Relay, through an authorized Global Relay reseller (“<span class="bold">Reseller</span>”), provides the Services to Customer and, if applicable, any Customer Affiliates (collectively “<span class="bold">Customer</span>”). These Master Terms of Service RCV also govern the subscription and use of Services by Customer under any document ordering Services issued by such Reseller (each an “<span class="bold">Order Form</span>”). Any then-current Order Form(s) together with these Master Terms of Service RCV form the “<span class="bold">Agreement</span>” between the Customer and Global Relay with respect to Services provided hereunder.</p>
								<p><span class="bold">1.2. Amendments.</span> Global Relay may update these Master Terms of Service RCV from time to time without further notice. The most current version will take effect upon posting at <a href="https://www.globalrelay.com/company-info/reseller-terms-of-service">https://www.globalrelay.com/company-info/reseller-terms-of-service</a>. By subscribing for, accessing, or using any services provided by Global Relay through Reseller, Customer agrees, without limitation or qualification, to be bound by these Master Terms of Service RCV.</p>
								<p><span class="bold">1.3. Representation &amp;Eligibility.</span> Each of Global Relay and Customer represents and warrants that: (a) it is properly licensed to do business and is in good legal standing in the jurisdictions in which it does business and will remain so during the term of the Agreement; (b) it has the right, power and authority to enter into, and to fully perform its obligations under the Agreement; (c) the information it has provided the other party under the Agreement is true, accurate, and complete in all material respects; and (d) the entering into and performance of the Agreement does not violate, conflict with, or result in a material default under any other contract or agreement to which it is a party, or by which it is bound. Each of Global Relay and Customer further represents and warrants that it shall conduct all of its activities under the Agreement in an honest, legal, ethical, businesslike, and professional manner.</p>
								<p><span class="bold">1.4. Affiliates.</span> Upon mutual agreement between the parties, Global Relay will provide the Services or any part of the Services to any Customer Affiliate as if such Services were provided directly to Customer. Except where Customer Affiliate has directly entered into an agreement or Statement of Work with Global Relay or unless otherwise agreed in writing by the parties, Customer shall (a) ensure that its Affiliates receiving the Services hereunder comply with all provisions of the Agreement applicable to Customer; (b) continue to act as a key point of contact with Global Relay with respect to facilitating the Services provided to its Affiliates; and (c) remain liable to Global Relay and, as between the parties, to all other Persons, for (i) the failure of Customer’s Affiliates to comply with the Agreement to the same extent that Customer would have been had Customer failed to comply; (ii) the acts and omissions of its Affiliates to the same extent that Customer would have been had Customer failed to comply, and (iii) all payments of the Fees owed by Customer’s Affiliates under the Agreement.</p>
								<p class="bold">2. GLOBAL RELAY SERVICES</p>
								<p><span class="bold">2.1. Services Subscription.</span> The services of Global Relay subscribed for or procured by Customer that are specifically itemized in the applicable Order Form shall be the "<span class="bold">Services</span>" provided by Global Relay pursuant to the Agreement.</p>
								<p><span class="bold">2.2. Order Form.</span> The Order Form that initiates the Services (issued by the Reseller) will at a minimum set out, in addition to the specific Services subscribed for by Customer, the subscription term (“<span class="bold">Term</span>”), Fees, Prices, initial User count, payment terms, Billing Cycle, and Effective Date for the commencement of the Services.</p>
								<p><span class="bold">2.3. Activation.</span> On or after the Effective Date of the Agreement and receipt of sign-up notification from Reseller, Global Relay will initiate activation of the Services subscribed for by Customer.</p>
								<p><span class="bold">2.3.1.    Provisioning.</span> Global Relay and Reseller, as applicable, will setup, activate, and test the Services on its Systems for Customer ("<span class="bold">Provisioning</span>").</p>
								<p><span class="bold">2.3.2.    Configuration.</span> Global Relay may take direction from Reseller, and such other person as may be identified by Reseller during the resold services sign-up process, as Customer’s IT Contact. Upon completion of Provisioning, Global Relay will provide Customer’s IT Contact with applicable specifications to enable Customer’s IT Contact to setup, configure, and test the Services, Accounts, and Users in Customer's Environment ("<span class="bold">Configuration</span>"). Customer’s IT Contact, has responsibility for, and control over, (a) the timely and accurate completion of the Configuration (including configuration of Users and User aliases, and supported versions of Third Party Networks if applicable), and (b) where Customer is using Global Relay Archive, verifying with Global Relay and Reseller the secure and proper end-to-end connection and message flow, including the sending, receipt, and archiving of messages in Global Relay Archive. Customer acknowledges that Global Relay is not liable for any loss resulting from the Configuration regardless of whether Global Relay supplied the software, instructions, or representatives of Global Relay to provide assistance with the Configuration. Unless otherwise scheduled between the parties in advance, Global Relay will be available to assist with Configuration during Business Hours.</p>
								<p><span class="bold">2.4. Evaluation.</span>For evaluation purposes, Global Relay may make available trial services, demo Accounts, or a proof of concept (POC) Environment for testing of certain Services (collectively, “<span class="bold">Trial</span>”). The scope, cost, and Trial Period for the Trial of any Services shall be set out in an Order Form. Services provided during the Trial are subject to the Agreement from the Effective Date of the Services unless otherwise agreed in writing by the parties.</p>
								<p><span class="bold">2.5. Service Availability.</span> Global Relay will make commercially reasonable efforts to provide Customer a high level of service availability, provided that Global Relay reserves the right to perform Regular Maintenance, or immediately implement Emergency Maintenance to prevent or remediate a Service impacting situation or security concern. Global Relay will endeavor to apply Emergency Maintenance during the time window set for Regular Maintenance, and to provide Customer with as much advance written notice as possible before any Maintenance.</p>
								<p><span class="bold">2.6. New Releases.</span> Customer acknowledges that Global Relay may provide automatic Releases to the Services from time to time, provided that with any such Release: (a) the Services will continue to meet all of Global Relay’s obligations under the Agreement, and (b) there will be no material deprecation, reduction, or degradation of the Services from the performance levels or material functionality of the Services contracted for under the Agreement. Global Relay will endeavor to provide Customer with reasonable advanced notice of any Release.</p>
								<p><span class="bold">2.7. Development Work.</span> In special circumstances, Global Relay may agree to perform certain customized Work requested by Customer related to the Services. The scope and cost of the Work to be performed by Global Relay must be set out in a Statement of Work, with applicable Acceptance Criteria, mutually agreed in writing by and directly between Customer and Global Relay.</p>
								<p class="bold">2.8. Support.</p>
								<p><span class="bold">2.8.1.	Standard Support.</span> Included with the Services, the following types of standard support (“<span class="bold">Support</span>”) are reasonably provided at no additional charge by Global Relay during Business Hours to Customer’s Administrative User(s), requesting support on behalf of Customer’s end Users, via email, phone, webinar, or remote desktop:</p>
								<ol type="a">
								    <li><span class="bold">Technical Support</span> to assist with troubleshooting and resolving Provisioning, Configuration, and operational issues. Additionally, support for network-related and urgent technical, security, or operational issues, is provided 24/7/365. Customer may open a Support Ticket via:</li>
								        <ol type="i">
								            <li>an email notification from Customer to support@globalrelay.net, or</li>
								            <li>a phone call from Customer to Support at 604.484.6630 or 866.484.6630.</li>
								        </ol>
								    <li><span class="bold">Training Support</span> to assist with setup of compliance and supervision tools, setup for data exports or self-directed eDiscovery/audit projects, and other training support related to the use of the Services.</li>
								</ol>
								<p><span class="bold">2.8.2.	Professional Services.</span> Customer may optionally engage Global Relay directly to perform any of the following additional professional services (“<span class="bold">Professional Services</span>”) in accordance with Global Relay’s standard rate or as otherwise agreed in writing by the parties:
								    <ol type="a">
								        <li><span class="bold">Audit &amp; eDiscovery Services</span> to assist with independent third party audit and eDiscovery projects carried out by Global Relay’s Compliance, Audit &amp; eDiscovery teams;</li>
								        <li><span class="bold">Data Services</span> to assist with consultative or customized support with respect to special requests or issues related to Customer’s Legacy Data or Archived Data; or</li>
								        <li><span class="bold">Technical Services</span> to assist with Standard Support outside of Business Hours, customized implementation/configuration, other consultative or project management services, or other advanced training or support beyond the scope of Support services outlined in Section 2.8.1 (Standard Support).</li>
								        </ol>
								<p><span class="bold">2.9. Control and Operation.</span> Subject to the terms of the Agreement, Global Relay will have control over the Provisioning, Support, operation, and maintenance of the Services and will determine the manner, methods, techniques, and procedures that Global Relay uses in providing the Services. Customer acknowledges and agrees that Global Relay cannot guarantee the successful operation of a Service where the Service may be affected by other Systems of Customer, Customer’s Environment, or Customer’s suppliers that are not maintained, operated, or controlled by Global Relay.</p>
								<p><span class="bold">2.10. FINRA Compliance Program.</span> (This paragraph only applies to FINRA CRP and FINRA CVD customers under the FINRA Compliance Program.) The Global Relay FINRA Compliance Program bundled Services offerings are exclusive to FINRA CRP and FINRA CVD customers of Global Relay. Global Relay reserves the right to modify its Global Relay FINRA Compliance Program bundled Services offering in the event FINRA makes any changes to the scope or status of Global Relay’s participation in the FINRA Compliance Program.</p>
								<p class="bold">3. PROPRIETARY RIGHTS</p>
								<p><span class="bold">3.1. Ownership and Control of Customer Data.</span> As between Global Relay and Customer, Customer will have sole and exclusive ownership of all right, title, and interest in and to Customer Confidential Information. Where Customer is using Global Relay Archive, Global Relay acknowledges that all Archived Data is proprietary to and exclusively owned by Customer. Nothing in the Agreement grants Global Relay any right, title, or interest in or to any Archived Data or other Customer Confidential Information other than as necessary to perform the Services. Customer’s Archived Data is managed and controlled via the actions of Customer and its Users. Accordingly, to the extent of its control, Customer is responsible for the Archived Data it stores in Global Relay Archive.</p>
								<p><span class="bold">3.2. Reservation of Rights in Services.</span> Other than the limited rights of the subscribing Customer to access and use the Services in accordance with the Agreement, no Intellectual Property Rights of a party will be transferred to the other. No other rights or ownership in the Services, express or implied, or any Intellectual Property Rights thereto are conveyed to Customer. Global Relay (or its licensors where applicable) is the exclusive owner of the Services and Works and reserves all of its rights, titles, and interest in and to the Services and Works, and any related Intellectual Property Rights, including all goodwill and any derivative works thereof, and anything developed or delivered by or on behalf of Global Relay under the Agreement. All rights, now and in the future, in and to the Services not expressly granted to Customer are reserved by Global Relay.</p>
								<p><span class="bold">3.3. Customer Feedback.</span> Global Relay shall have the right and sole discretion to use or incorporate into the Services any suggestions, enhancement requests, recommendations, or other feedback provided by Customer or its Users, relating to the operation of the Services, without payment to or ownership by Customer.</p>
								<p class="bold">4. CUSTOMER RESPONSIBILITIES AND USE OF SERVICES</p>
								<p><span class="bold">4.1. Administrative User.</span> Customer shall appoint one or more Administrative User(s) to be responsible for managing Customer’s Users, Accounts and Passwords, as well as communicating Customer Instructions. For mutual security of Customer and Global Relay, each Administrative User must be appointed and removed (as applicable) by Customer delivering to Global Relay an executed Appointment of Administrator Form. At least one Administrative User must be appointed before any part of the Services can be accessed by Customer.</p>
								<p><span class="bold">4.2. Customer Instructions.</span> Customer agrees that each of its Administrative User(s) will have responsibility for all Customer Instructions. Each Administrative User, as a representative of Customer, has the ability, at the sole discretion of Customer, to further assign its administrative privileges and access controls under the Administrative Account to other Accounts or Users of Customer. Customer hereby authorizes Global Relay to accept and act on any requests or directions pursuant to a Customer Instruction or otherwise from an Administrative User or any Person that has been assigned such administrative privileges or access controls by an Administrative User. In no event shall Global Relay be liable to Customer or any third party for such reliance by Global Relay on any Customer Instruction in a manner consistent with this paragraph.</p>
								<p><span class="bold">4.3. Decline to Act.</span> For mutual security of Customer and Global Relay, Global Relay may, in its reasonable discretion and in good faith, decline to act on a Customer Instruction until it is able to verify the validity of the Customer Instruction or the requesting Administrative User. Global Relay shall not incur any liability for exercising its discretion in a manner consistent with this paragraph.</p>
								<p><span class="bold">4.4. Access.</span> Customer understands and acknowledges that Global Relay is not responsible for maintaining Accounts and Passwords for Users of Customer. Customer’s Administrative User(s) will have access rights to the online Control Center to directly manage Customer's role-based access controls and use of the Services. Customer shall be responsible and liable for any and all access to and use of the Services by Customer’s Users. Specifically, Customer’s responsibilities shall include, but are not limited to, (a) maintaining and managing User Accounts and Passwords; (b) maintaining the confidentiality and security of Customer access information associated with Accounts and Passwords, or other account identifiers which Customer chooses or is assigned for its Users; (c) all activities that occur under such Accounts and Passwords in connection with the Services; (d) Users identification and authentication for access to the Services; and (e) the security of Customer’s own Password authentication servers if Customer’s servers are used by Customer as part of the login authentication process.</p>
								<p><span class="bold">4.5. Restrictions on Use.</span> Customer is responsible for its Users’ compliance with the Agreement and Applicable Laws. Except as expressly provided under the Agreement, Customer shall not and shall not cause or permit others to: (a) rent, sell, assign, lease, sublicense, transfer, redistribute, or encumber the Services, or otherwise make the Services available to or for the benefit of any other Person who is not a subscriber of the Services via Customer; (b) derive or attempt to derive the source code, source files, or structure of all or any portion of the Services by reverse engineering, disassembly, de-compilation, or any other means, or otherwise modify, adapt, or create derivative works from the Services; (c) send or store infringing or unlawful material or malware; (d) attempt to gain unauthorized access to, or disrupt the integrity or performance of, the Services or Data contained in the Systems; (e) use or access the Services for the purpose of developing any application, software, product, or service that does or could in any way compete, interact, or interfere with the Services, except as permitted in writing by Global Relay;  (f) use or access the Services for the purpose of building a competitive product or service or copying its features or user interface; (g) use the Services, or permit them to be used, for purposes of product evaluation, benchmarking or other comparative analysis intended for publication, or to share, distribute, or disclose the results of any benchmarking tests, comparative evaluations, or its internal assessments or audits of the Services with any third party without Global Relay’s prior written consent in each case. Additionally, for security purposes, Customer shall not, and shall not cause or permit others to, (h) perform social engineering, penetration, and other similar security or vulnerability testing on Global Relay’s Environment without the prior written consent of Global Relay in each case; or (i) cause or use any application to negatively impact, including overloading, spamming, obstructing, or interfering with, the stability or performance of Global Relay’s Systems or Environment. Any illegal or unauthorized use or abuse of the Services or Data is strictly prohibited. Global Relay reserves the right to terminate the Services, in whole or in part, if in its reasonable discretion it determines that any component of the Services or Data is being used by or via Customer for an illegal or unauthorized purpose or in any manner inconsistent with the terms of this Agreement. Customer agrees to notify Global Relay promptly upon becoming aware of any unauthorized access or use.</p>
								<p><span class="bold">4.6. Acceptable Use Policy.</span> Customer acknowledges that the Services provided to Customer pursuant to the Agreement are also subject to, and Customer agrees that it shall comply with, Global Relay’s Acceptable Use Policy located at <a href="http://www.globalrelay.com/policies/acceptable-use">http://www.globalrelay.com/policies/acceptable-use</a>, as updated from time to time.</p>
								<p class="bold">5. GLOBAL RELAY ARCHIVE</p>
								<p>These additional terms apply where Customer is using Global Relay Archive Services.</p>
								<p><span class="bold">5.1. Archive Data Capture.</span> Customer shall ensure that: (a) Global Relay, either directly or via Reseller, is provided a complete and accurate list of all email domains and other types of electronic communications to be archived, including any updates to the same; (b) Global Relay, either directly or via Reseller, is provided a complete and accurate list of Customer’s Users and User aliases, as applicable, including any updates to the same; (c) Global Relay, either directly or via Reseller, is provided with any requirements regarding physical and logical segregation of Customer Data within Global Relay Archive before Provisioning commences; (d) Configuration of all electronic communications required to be archived are completed in accordance with Global Relay’s specifications; (e) all electronic communications required to be archived is properly formatted in accordance with industry standards supported by Global Relay’s specifications, and successfully delivered to Global Relay Archive for ingestion; (f) any Legacy Data Import is provided to Global Relay in an industry standard format which has been tested and verified by Global Relay as supported by Global Relay Archive; and (g) it verifies that the data types and Third Party Networks (including versions and formats) it requires to be archived are in fact supported by Global Relay Archive and set out in the applicable Order Form (see https://www.globalrelay.com/support-training/help-center for supported data types and Third Party Networks (including versions and formats), or contact Global Relay to inquire about a data type or version not listed). Customer is prohibited from delivering Third Party Networks data types which have been converted into email formats to Global Relay Archive to be captured as standard email messages without formally adding such data types to the Services through a Change Order. Global Relay, either directly or via Reseller, reserves the right to charge a Fee for each of such Third Party Networks data type delivered as email messages. Global Relay is not responsible to Customer for any message types or Third Party Networks (including versions and formats) that are not supported, or that are not technically able to be captured or ingested by Global Relay Archive for reasons beyond the control of Global Relay.</p>
								<p><span class="bold">5.2. Monitoring Data Flow.</span> Customer shall monitor its delivery of each data type to Global Relay Archive. Upon Customer’s written request, Global Relay will generate a daily email to Customer that reports statistics on Global Relay’s receipt and processing of each data type from Customer and each Customer User. Customer is responsible to review these reports and to notify Global Relay of any mail flow issues, anomalies, or delivery failures. Customer shall also notify Global Relay of any upgrades, patches, or maintenance to Customer’s servers or data feeds which may result in an outage, disablement of journaling, or other disruption of data flow to Global Relay Archive. Customer shall ensure that no data or messages are transmitted through its email/IM server(s) or otherwise, until Customer’s upgrade, patch, or maintenance has been completed and journaling or data flow to Global Relay Archive has been enabled or reactivated.</p>
								<p class="bold">6. THIRD PARTY NETWORKS</p>
								<p>These additional terms in Section 6 (Third Party Networks) apply where Customer is using any Services that interoperate with any Third Party Networks, or Email Services.</p>
								<p><span class="bold">6.1. Availability of Third Party Networks.</span> Global Relay does not control and is not responsible for any Third Party Networks. Such Third Party Networks may change their formats, APIs, delivery methods, or posting times without notice to Global Relay, or may have inaccuracies in format schemas, corruptions or other changes, which may affect the availability or performance of the Services that interoperate with Third Party Networks. Notwithstanding anything else in the Agreement, Global Relay does not and cannot warrant the availability or performance of any Third Party Networks, and Global Relay expressly disclaims any and all liability related to, connected with, or arising from Third Party Networks including any outages, delivery delays, delivery methods, corruption of data, processing failures, failure to format data in accordance with such Third Party Network’s data schema, changed or discontinued or failed services, or termination of service. Additionally, Customer is responsible to ensure its end Users only use versions of the applicable Third Party Network or Email Services clients that are expressly supported by Global Relay Services. Customer may contact Global Relay Support to confirm an updated list of supported Third Party Networks (currently listed here: https://www.globalrelay.com/support-training/help-center). Global Relay also reserves the right to discontinue support for any Third Party Network service, temporarily or permanently, upon reasonable advanced notice. Customer agrees that Global Relay shall not be liable to Customer or any third party for any modification or discontinuance of any of the Services; provided however, that in the event Global Relay discontinues any Services, Global Relay will endeavor to provide Customer with reasonable advanced notice. To assist with the administration and maintenance of accurate data flow and user statistics, where an end User of an Account associated with a particular Third Party Network or an Email Service has not accessed that particular Account for more than 90 consecutive days, the User’s license related to such Account will be deemed abandoned and Global Relay may adjust Global Relay’s license count with such Third Party Network or Email Services to account for such User’s inactivity. To regain access, Customer may contact Global Relay Support.</p>
								<p><span class="bold">6.2. Third Party Networks Terms of Use.</span> Customer acknowledges its obligation to comply with any terms of service or terms of use provided by, or any usage fees required by, any Third Party Network or federation of Third Party Networks, including any limitation with respect to restricted or illegal activities. Global Relay shall not be liable for Customer's violation of any such Third Party Network's requirements and Customer shall hold Global Relay harmless for any liability for such violations.</p>
								<p class="bold">7. SECURITY</p>
								<p class="bold">7.1. Security Procedures and Controls.</p>
								<p><span class="bold">7.1.1.	Global Relay.</span> In connection with delivery of the Services and its obligations under the Agreement, Global Relay has implemented and will continually maintain appropriate security procedures, measures, and controls, including appropriate electronic, physical, and organizational security procedures, measures, and controls to reasonably guard against accidental, unauthorized, or unlawful access, destruction, use, alteration, modification, disclosure, or loss of Archived Data.</p>
								<p><span class="bold">7.1.2.	Customer.</span> In connection with its use of the Services and its obligations under Section 4 (Customer Responsibilities and Use of Services), Customer will continually maintain appropriate security procedures, measures, and controls, including appropriate electronic, physical, and organizational security procedures, measures and controls to reasonably guard against accidental, unauthorized, or unlawful access, destruction, use, alteration, modification, disclosure, or loss of Archived Data.</p>
								<p><span class="bold">7.2. Data Protection.</span> Notwithstanding any other provisions of the Agreement, Global Relay reserves the right, in the event of a reasonable detection or perceived detection of suspicious activity or other security issues whatsoever, including an incident that impacts internet security infrastructure or transmissions in a manner which may cause security risk to Global Relay, Customer, or Archived Data, to temporarily suspend Customer’s access to any of the Services as is necessary. During any such suspension, Global Relay will use commercially reasonable efforts to resolve and mitigate the risk and resume Customer's use of the Services and access to the Archived Data as soon as possible and to ensure the integrity of the Archived Data. Any such suspensions will only be in effect during and no longer than a period equal to the time necessary to eliminate risk to Global Relay Services and the Archived Data.</p>
								<p class="bold">8. CONFIDENTIALITY &amp; NON-DISCLOSURE</p>
								<p><span class="bold">8.1. Protection of Confidential Information.</span> The parties to the Agreement shall not use any Confidential Information (which term shall include Archived Data) of the other party for its own benefit or for any purpose other than to fulfill its respective obligations under the Agreement. Each party agrees to receive and preserve such Confidential Information as proprietary and confidential information, exercising the same degree of care a reasonable and careful person would exercise with its own confidential information, and in no case will it use less than commercially reasonable efforts consistent with the standards of practice in the industry to prevent unauthorized access to and disclosure of the other party’s Confidential Information. The parties further agree that neither will make Confidential Information of the other party available in any form to, or for the use or benefit of, any Person except as provided in the Agreement, and that neither will use any Confidential Information of the other, or the Services, to compete with the other party in its business.</p>
								<p class="bold">8.2. Non-Disclosure Obligations.</p>
								<p><span class="bold">8.2.1.	Non-Disclosure.</span> Neither party shall disclose the Confidential Information of the other party to any Person except:</p>
								<ol type="a">
								       <li>to its employees and non-employee representatives who need to know the information to fulfill its respective obligations under the Agreement or in connection with the Services, and are bound by confidentiality obligations no less protective than those in the Agreement;</li>
								    <li>where disclosure is required or authorized by Applicable Law or required, compelled, or requested by Governmental or Regulatory Authority or administrative or judicial process or proceeding (collectively "<span class="bold">Legal Process</span>"); or</li>
								        <li>with prior written consent of the other party.</li>
								    </ol>
								<p><span class="bold">8.2.2.	Notice.</span> In the event that a party is legally compelled under Legal Process to provide access to the Archived Data or other Confidential Information of the other party, then the disclosing party undertakes, to the extent legally permissible, to promptly provide the other party with written notice of such an event so as to afford the other party the opportunity (at such other party’s cost) to limit, monitor, control or prevent the disclosure. A party’s obligation to provide written notice and the opportunity under the foregoing sentence shall not be interpreted as preventing that party from meeting a deadline or other requirements under Applicable Law or Legal Process. Customer is responsible for all costs to comply with Legal Process and any related disclosure of its Archived Data.
								<p><span class="bold">8.3. Publication.</span> Global Relay has the right to refer to Customer (without using name or logo) for general information and business purposes regarding Global Relay's customer base. Global Relay shall not issue any press release announcing the engagement or use by Customer of the Services without the express prior written consent of Customer. Any press release or case study shall be subject to the review and prior written approval of both parties and this approval shall not be unreasonably delayed or withheld.</p>
								<p class="bold">9. FEES, PAYMENTS &amp; CHANGE ORDERS</p>
								<p><span class="bold">9.1. Fees and Payments.</span> Where Customer subscribes for the Services through a Reseller, the contractual provisions governing fees and payment terms shall be set out in the Order Form or other agreement between Customer and Reseller. Customer is responsible for providing complete and accurate billing and contact information, including updates to User counts related to the Services, and for promptly notifying Reseller of any changes to such information.</p>
								<p><span class="bold">9.2. Change Orders.</span> Customer may request New Services from time to time during the Term. “<span class="bold">New Services</span>” are services that are materially different from or in addition to the Services described in the then-current Order Form(s). New Services may include, but not limited to, adding new data types to be archived, adding ancillary Services, additional functionality, customization of support packages, the import of Legacy Data, or other requirements of Customer that alter the original scope of the Services (but do not constitute Work under Section 2.7 (Development Work)). Customer may be required to execute a Change Order, directly with Global Relay or with Reseller depending on the nature of the New Services, which sets out the New Services subscribed for by Customer, associated costs, scope, and any additional obligations or effects on the Services set out in the then-current Order Form(s). New Services will be billable from the effective date of the Change Order at the rate specified therein. New Services will be coterminous with the Term for the existing Services, unless otherwise agreed in writing between Global Relay and Customer. </p>
								<p><span class="bold">9.3. True-ups.</span> Customer may increase its User subscriptions during the Term, provided that Customer promptly reports any increases in User counts to Reseller. Global Relay, directly or via Reseller, reserves the right to perform a reconciliation of actual usage/User count versus ordered quantities of Customer’s Service/User subscriptions under the then-current Order Form(s) ("<span class="bold">True-up</span>"). Global Relay shall have the right to audit, and where applicable Customer agrees to make available, or provide access to, Customer’s records reasonably necessary to assist with the True-up. If, as a result of any such True-up or audit, Global Relay reasonably determines that Customer’s use of the Services has exceeded its subscription quantities, or where Customer has reported an increase in User subscriptions, Global Relay, directly or via Reseller, will make the pro-rated adjustments to the corresponding Fees from the start of such excesses or increases and invoice these fees in the subsequent invoice(s) or in a separate True-up invoice.</p>
								<p><span class="bold">9.4. Subscription Minimum.</span> Subject to Section 9.3 (True-ups), the initial User count stated in Customer’s Order Form (as communicated by Reseller to Global Relay during Customer signup) or the average User count over the last 12 months, whichever is higher, will be the minimum billable commitment of Customer, unless otherwise agreed in writing by the parties.</p>
								<p class="bold">10. WARRANTIES AND DISCLAIMERS</p>
								<p>GLOBAL RELAY IS COMMITTED TO MAKING COMMERCIALLY REASONABLE EFFORTS TO PROVIDE CUSTOMER A HIGH LEVEL OF SERVICE AVAILABILITY, SUBJECT TO CUSTOMER’S AND CUSTOMER’S THIRD PARTY NETWORKS AND VENDORS’ COOPERATION AND COMPLIANCE WITH THE AGREEMENT. NOTWITHSTANDING THE FOREGOING, TEMPORARY UNAVAILABILITY OF THE SERVICES MAY OCCUR AS A RESULT OF MAINTENANCE, SOFTWARE RELEASES, HARDWARE RELEASES, SECURITY ISSUES, INTERNET ISSUES, OR CONNECTIVITY ISSUES. EXCEPT AS OTHERWISE EXPRESSLY STATED IN THE AGREEMENT, CUSTOMER EXPRESSLY UNDERSTANDS AND AGREES THAT CUSTOMER’S USE OF THE SERVICES IS AT ITS SOLE RISK. THE SERVICES ARE PROVIDED BY GLOBAL RELAY, AND ACCEPTED BY CUSTOMER, ON AN "AS IS" AND "AS AVAILABLE" BASIS. GLOBAL RELAY AND ITS SUPPLIERS AND RESELLERS, TO THE FULLEST EXTENT PERMITTED BY LAW, OTHERWISE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY AND NON-INFRINGEMENT OF PROPRIETARY OR THIRD PARTY RIGHTS, OR ABOUT THE ACCURACY, SECURITY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF ITS SERVICES, SOFTWARE, OR CONTENT, OR THAT THE SERVICES ARE ERROR-FREE. GLOBAL RELAY EXPRESSLY DISCLAIMS ANY REPRESENTATIONS OR WARRANTIES THAT CUSTOMER’S USE OF THE SERVICES WILL SATISFY ANY OF ITS STATUTORY OR REGULATORY OBLIGATIONS, OR WILL ASSIST WITH, GUARANTEE, OR OTHERWISE ENSURE COMPLIANCE WITH CUSTOMER’S LEGAL REQUIREMENTS, OR ANY APPLICABLE LAWS OR REGULATIONS. CUSTOMER ASSUMES ALL RESPONSIBILITY FOR DETERMINING WHETHER THE SERVICES ARE SUFFICIENT FOR CUSTOMER’S PURPOSES WITH RESPECT TO CUSTOMER’S REQUIREMENTS UNDER APPLICABLE LAWS. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT CUSTOMER'S DISCRETION AND RISK AND CUSTOMER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO ITS SYSTEMS OR ENVIRONMENT, OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE, INFORMATION, INSTRUCTIONS, OR COST PROJECTIONS, WHETHER ORAL OR WRITTEN, FROM GLOBAL RELAY OR ITS EMPLOYEES, REPRESENTATIVES, OR AGENTS, OR THROUGH OR FROM USE OF THE SERVICES SHALL CREATE ANY PROMISE, WARRANTY, OR OBLIGATION NOT EXPRESSLY STATED IN THE AGREEMENT.</p>
								<p class="bold">11. RELEASE</p>
								<p>Customer releases Global Relay from and agrees to defend, indemnify, and hold harmless Global Relay, its Affiliates, directors, officers, employees, agents, and Reseller from and against any claims, actions, suits, demands, proceedings brought by third parties (collectively “<span class="bold">Claims</span>”) and any related damages, losses, liabilities, obligations, judgments, awards, costs, or expenses, including reasonable legal fees (collectively “<span class="bold">Damages</span>”), to the extent connected with, arising out of, or related to Customer's: (a) negligence or misuse of the Services, (b) breach of the Agreement, or (c) use of Third Party Networks or combination of the Services with other products, processes, or material not provided by Global Relay, whether or not due to any act, error, omission, or negligence by Global Relay or any of its affiliates, officers, directors, employees, agents, Reseller, or others whom it is in law responsible.</p> 
								<p class="bold">12. LIMITATION OF LIABILITY</p>
								<p><span class="bold">12.1. Exclusion of Damages.</span> Notwithstanding any other provision of the Agreement or any other related agreements, in no event shall Global Relay be liable to Customer, its clients, or any other party (any of which, a "<span class="bold">Person</span>") under or in relation to the Agreement for any special, direct, indirect, incidental, consequential, punitive damages, or loss of use, loss of production, loss or corruption of data, loss of profits or revenues, loss of markets, economic loss, loss of good will, exemplary loss, anticipated or otherwise, that may be suffered or incurred by any Person, resulting from any matter under or related to the Agreement or the use of, inability to use or access, or performance of any of the Services, and notwithstanding that such party may have been advised of the possibility of any such damages and regardless of whether any of the foregoing is determined to constitute a fundamental breach or failure of essential purpose.</p>
								<p><span class="bold">12.2. Limit.</span> Notwithstanding any other provision of the Agreement, the aggregate liability of Global Relay to Customer or any Person whatsoever arising out of, in connection with, or related to the Services or the Agreement, whether in contract or tort or under any other theory of liability, including without limitation for any breach of or default under the Agreement or any misrepresentation or negligence, in the aggregate, shall be limited to proven direct damages caused by Global Relay in an amount not to exceed the amount of monthly recurring Fees Customer has paid Reseller for the Services in respect of the three months preceding the event giving rise to the liability. This limit is cumulative and the existence of more than one event will not enlarge the limit. The parties acknowledge that these limitations of liability and the allocation of risk, including waiver of consequential damages, are an essential element of the bargain between the parties and part of the consideration for the agreed upon Prices and Fees, and in their absence the Prices and Fees and the Agreement would be substantially different. No action, regardless of form, relating to the Agreement or the Services may be brought by either Party more than two years after the cause of action has accrued under Applicable Laws.</p>
								<p><span class="bold">12.3. Mitigation.</span> Each party will have a duty to mitigate damages for which the other party is responsible.</p>
								<p class="bold">13. TERM, SUSPENSION, AND TERMINATION</p>
								<p><span class="bold">13.1. Term.</span> The Agreement will commence on the Services start date set out in the Order Form and continue for the Term set out therein, unless earlier terminated in accordance with the Agreement or otherwise agreed in writing. </p>
								<p><span class="bold">13.2. Suspension.</span> Without limiting other remedies, Global Relay reserves the right to suspend any and all of Customer’s Services if: (a) Customer is in material breach or default in the performance of its obligations under an agreement between Customer and Reseller; or (b)  Customer is in material breach or default in performance of its obligations under the Agreement or any agreement between Customer and Global Relay, or has otherwise violated the Agreement. Customer shall resolve or cure the specific concerns to Global Relay's (and to Reseller's, if applicable) reasonable satisfaction prior to the Services being reinstated. Global Relay will not be liable to Customer for any suspension effected in accordance with this Section 13.2 (Suspension), and the Fees will continue to apply and accrue during any such suspension.</p>
								<p class="bold">13.3. Termination. </p>
								<p><span class="bold">13.3.1.	Termination by Customer.</span> Customer may terminate the Agreement in accordance with the notice requirement of the Order Form or other agreement between Customer and Reseller, and such termination is communicated in writing by Reseller to Global Relay.  </p>
								<p><span class="bold">13.3.2.	Termination by Global Relay.</span> Global Relay may terminate the Agreement: (a) for cause upon Customer’s material breach or default in performing its material obligations under the Agreement; (b) immediately if the Order Form is terminated for any reason; or (c) on 60 days’ Notice to Customer. Global Relay’s termination of the Agreement will not impact any other rights or obligations provided under the Order Form unrelated to Global Relay Services.</p>
								<p><span class="bold">13.3.3.	Continued Use.</span> If Customer continues to use the Services to preserve its Archived Data after the Agreement has been terminated, then, unless Customer executes an Order Form for the Services directly with Global Relay or otherwise comes to a mutual agreement in writing with Global Relay, Global Relay has the right, without further notice, to: (a) charge Customer for its use of the Services at Global Relay’s Tariff Rate, (b) suspend Customer’s access, (c) disable ingestion of data into Customer’s Global Relay Archive, and/or (d) delete Customer’s Archived Data in accordance with Section 13.4 (Return or Disposition of Archived Data). Global Relay will invoice Customer directly for any Fees associated with Customer’s continued use.</p>
								<p><span class="bold">13.4. Return or Disposition of Archived Data.</span> Customer may:</p>
								    <ol type="a">
								        <li>engage Global Relay directly to export a copy of its Archived Data stored by Customer in its Global Relay Archive, at Global Relay’s standard rates, based on the digital media and file format requested and amount of Archived Data to be returned; or</li>
								        <li>direct Global Relay to permanently delete and dispose the Archived Data.</li>
								    </ol>
								<p>In the event that Customer has not engaged Global Relay to export a copy of its Archived Data in accordance with Section 13.4 (a) within 60 days following the effective termination of Services, including termination of Services for non-payment (collectively, the "<span class="bold">Abandonment Date</span>"), then Customer is hereby put on notice that Global Relay may, without incurring any liability, securely delete Customer’s Archived Data after the Abandonment Date, and is otherwise not responsible for any of Customer's Archived Data that remains in Global Relay Archive after the Abandonment Date.</p>
								<p><span class="bold">13.5. Survival.</span> The following will survive the termination of the Agreement: Section 3 (Proprietary Rights), 8 (Confidentiality &amp; Non-Disclosure), 10 (Warranties and Disclaimers), 11 (Release), 12 (Limitation of Liability), this Section 13 (Term, Suspension and Termination), Section 14 (Miscellaneous), and any other provisions of the Agreement that by their nature should survive termination of the Agreement.</p>
								<p class="bold">14. MISCELLANEOUS</p>
								<p><span class="bold">14.1. Relationship of the Parties.</span> Customer acknowledges that Global Relay, as a service provider, is an independent contractor, and the parties agree that no agency, partnership, joint venture, employee-employer, or franchiser-franchisee relationship is intended or created by the Agreement. Neither party shall have any authority to act for, bind, make any representations or warranties, or assume any obligation or responsibility, express or implied, on behalf of the other party, except as specifically authorized under the Agreement or by written direction of the other party. Each party is solely responsible for all expenses associated with its performance under the Agreement unless otherwise specifically indicated. Except as expressly set out herein, no third party beneficiary relationships are created by the Agreement. Nothing in the Agreement shall restrict in any way the freedom of either party to conduct as it sees fit any other business or activity whatsoever.</p>
								<p><span class="bold">14.2. Assignment.</span> The Agreement may not be assigned by either party without the other party's prior written consent, which will not be unreasonably withheld, conditioned or delayed. Notwithstanding the foregoing, either party may assign the Agreement to an Affiliate or successor entity upon 30 days’ Notice to the other party.</p>
								<p><span class="bold">14.3. Enurement.</span> The Agreement will enure to the benefit of and is binding upon the parties to the Agreement and their respective successors and permitted assigns.</p>
								<p><span class="bold">14.4. Notices and Communications.</span> All Notices (other than Customer Instructions) required or provided by way of the Agreement shall be in writing and shall be deemed to have been given when delivered (with proof of successful delivery) via: (a) email (with confirmation of receipt), (b) mail (registered or certified, postage prepaid with receipt requested), (c) courier, or (d) personally. With respect to Notice via email, each party may rely on Customer Instructions and Notices as if the sender, on behalf of the party, had given them signed and in writing. Any Notice delivered to Global Relay or Customer shall be sent to the following contacts, as appropriate, depending on the subject matter of the Notice:</p>
							    <p>
					                <span class="bold">To Global Relay:</span><br/>
					                Attention: Legal, with a copy to: Shannon Rogers, CLO<br/>
					                220 Cambie St., 2nd Floor, Vancouver, BC V6B 2M9, Canada,<br/>
					                General Phone: 604.484.6630<br/>
					            </p>
					            <p><span class="bold">To Customer:</span> the address provided by Customer to Reseller.</p>
					            <table border="1" style="margin-bottom:20px;">
					                <tr class="bold">
					                    <td>Party</td><td>Issue</td><td>Contact</td><td>Email Address</td>
					                </tr>
					                <tr>
					                    <td class="bold" rowspan="3">Global Relay</td><td>IT Support</td><td>Support Desk</td><td>support@globalrelay.net</td>
					                </tr>
					                <tr>
					                    <td>Billing/Fees</td><td>Accounting</td><td>accounting@globalrelay.net</td>
					                </tr>
					                <tr>
					                    <td>Legal/contractual</td><td>Legal</td><td>legal@globalrelay.net</td>
					                </tr>
					                <tr>
					                    <td class="bold">Reseller</td><td>Termination Notice </td><td>Reseller Contact</td><td>Reseller Contact</td>
					                </tr>
					                 <tr>
					                    <td class="bold" rowspan="3">Customer</td><td>IT Support</td><td>Administrative User</td><td>admin@customerdomain or alternatively designated contact</td>
					                </tr>
					                <tr>
					                    <td>Billing/Fees</td><td>Administrative User</td><td>admin@customerdomain or alternatively designated contact</td>
					                </tr>
					                <tr>
					                    <td>Legal/contractual</td><td>Administrative User</td><td>admin@customerdomain or alternatively designated contact</td>
					                </tr>
					            </table>
					
								<p>In the event that Customer has not provided Global Relay with up-to-date or accurate contact information, then Global Relay may provide Notice to Reseller, and such Notice will be deemed to have been provided to Customer. </p>
								<p><span class="bold">14.5. Force Majeure.</span> Global Relay shall not be liable for any failure of Global Relay to perform any of its obligations under the Agreement during any period in which such failure to perform arises directly or indirectly out of a Force Majeure event, provided that Global Relay promptly notifies the other party of such delay in writing and uses its commercially reasonable efforts to minimize the adverse effect of such events.</p>
								<p class="bold">14.6. Entire Agreement.</p>
								<p><span class="bold">14.6.1.	Entire Agreement.</span> The Agreement is comprised of the Master Terms of Service RCV, including any amendments, applicable Order Form(s), and the most current edition of all schedules or policies referred to in the Agreement. These together constitute the entire understanding and agreement between the parties for the provision and use of the Services and supersede any and all prior agreements, correspondence, understandings and discussions, whether written or oral, relative to this subject matter. For clarity, other than the documents listed above that constitute the Agreement, no other terms or conditions contained in any Reseller documentation shall govern the Services.
								For clarity, the Agreement (incorporating the Master Terms of Service RCV) solely applies to the Services of Global Relay provided to Customer via Reseller. In the event that Customer engages Global Relay directly to provide certain services, which may include but are not limited to any archiving services not set out in the Order Form of Reseller, any Professional Services, ancillary services, or Work (collectively “Direct Services”), then such Direct Services will be governed by the Master Terms of Service located at: <a href="https://www.globalrelay.com/company-info/terms-of-use#terms">https://www.globalrelay.com/company-info/terms-of-use#terms.</a> </p>
								<p><span class="bold">14.6.2.	Order of Priority.</span> Any conflict or inconsistency in the interpretation of the Agreement shall be resolved by giving precedence according to the following order of priority: 1) the Master Terms of Service RCV, 2) any applicable Schedules or the Policies listed in Section 14.6.4 (Schedules), unless the applicable Schedule or Policy specifically states that any part of it takes precedence over the provision of the Master Terms of Service RCV, and 3) the applicable Order Form(s) with the most recent prevailing. </p>
								<p><span class="bold">14.6.3.	Definitions &amp; Interpretation.</span> In the Agreement, all capitalized terms, unless specifically defined herein, have the meanings contained in the Standard Definitions (located here and at: <a href="https://www.globalrelay.com/policies/standard-definitions">https://www.globalrelay.com/policies/standard-definitions</a>, incorporated by reference as Schedule A) to the Agreement. Any conflict or inconsistency between the Standard Definitions and the terms specifically defined in the Agreement (without reference to Schedule A), the parties intend for the definitions contained in the Agreement to prevail over the Standard Definitions. The word “including”, “include” and “includes” shall be interpreted to be mean including/include/includes without limitation unless the context otherwise requires.</p>
								<p><span class="bold">14.6.4.	Schedules.</span> As of the Effective Date, the following Schedule(s) are incorporated herein by reference and deemed to be a part of the Agreement: </p>
								    <ol type="a">
								        <li><span class="bold">Schedule A</span> 	Standard Definitions</li>
								    </ol>
								<p><span class="bold">14.7. Severability and Non-waiver.</span> If any part of the Agreement is found to be invalid, all other parts of the Agreement remain enforceable. Either party's failure to act with respect to a breach or default by the other party does not waive the non-defaulting party's right to act with respect to subsequent or similar breaches or defaults.</p>
								<p><span class="bold">14.8. Governing Law.</span> The Agreement shall be governed by and construed in accordance with the laws applicable in the Province of British Columbia and the laws of Canada applicable therein, excluding that body of law governing conflict of laws. Any action or proceeding brought to enforce the terms of the Agreement will be brought in a court of competent authority in Vancouver, British Columbia. The parties submit to the exclusive jurisdiction of this court. EACH PARTY HERETO IRREVOCABLY WAIVES ANY RIGHT TO A TRIAL BY JURY IN ANY ACTION OR PROCEEDING RELATING TO OR ARISING OUT OF THE AGREEMENT.</p>
								<p><span class="bold">14.9. Dispute Resolution.</span> In the event of a dispute between Global Relay and Customer, the dispute will be escalated internally in good faith; first through designated Global Relay personnel and this person's equivalent at Customer; then through another designated Global Relay personnel and this person's equivalent at Customer. All negotiations pursuant to this clause are confidential and shall be treated as compromise and settlement negotiations for purposes of applicable rules of evidence. Any dispute arising out of or relating to this Agreement, including the breach, termination or validity hereof, which has not been resolved by the foregoing negotiation procedure within 90 days of the initiation of such procedure, may then otherwise be dealt with according to the provisions of this Agreement. This dispute resolution procedure will not affect the obligation of either party to perform, subject to Global Relay’s right to suspend Services in accordance with Section 13.2 (Suspension) or the right of either party to enforce this Agreement.</p>
								<p><span class="bold">14.10. Non-Solicitation.</span>  During the Term of the Agreement and for a period of six months after the end of the last Term, and except as otherwise agreed in writing, Customer will not, directly or indirectly, (a) employ or hire any person who is at the time in question, or who was at any time during the immediately preceding six months, employed by Global Relay, or (b) cause, invite, solicit, entice, or induce any person who is at the time in question, or who was at any time during the immediately preceding six months, employed by Global Relay, to terminate such person’s employment with Global Relay, unless expressly consented to in writing by Global Relay in each case.</p>
								<p><span class="bold">14.11. Electronic Signatures and Contracts.</span> Customer's use of the Services includes the ability to enable Customer's Administrative User(s) to: electronically enter into agreements via Global Relay's website, digital signature or email. Customer acknowledges such electronic submissions by Customer’s Administrative User(s) constitutes Customer's agreement and intent to be bound by the same and to pay for such Services, Change Orders, agreements and purchases.</p>
								<p><span class="bold">14.12. Accepted Terms.</span> Global Relay AoA Forms and other Global Relay forms, incorporating by reference these Master Terms of Service RCV, may be executed by original, digital signature, email transmission of a .pdf or image file format document, or otherwise, in one or more counterparts, each of which shall be deemed an original, but all of which together shall constitute one and the same document.</p>

							</div>
							
						</div>
					
					</div>
				
				</div>
				<div id="back-top">BACK TO TOP</div>
			</div>
			
			<%@ include file="../../includes/footer.jsp" %>
			<script src="${baseUrl}/template-resources/javascripts/internal/scroll_function.js"></script>
	</body>
</html>